server:
  port: 9000
spring:
  mail:
    host: smtp.qq.com
    username: 670115782@qq.com
    password: nvjyqdkscropbfha
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true

  #redis
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

#mybatis
mybatis:
  type-aliases-package: com.blog.framework.model
  configuration:
    map-underscore-to-camel-case: true

mapper:
  identity: MYSQL


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count = countSql


#激活地址
activation-address: http://192.168.10.170:6090/#/msg?urlState=urlInvalid&param={1}

#管理员账号密码
admin:
  username: admin
  password: liu133297

file:
  uploadPath: E:\temp\file\